### ISSUE TITLE
Komplettering

### ISSUE THREAD

**Issue by axeberg** [chas-academy/berserkers-06-imdb-clone#149]
Here are the requirements that are not met for this hand-in. Please prioritize these before anything else:

- [x]  **En inloggad del som då kräver registrering där man som användare:**
    - [x]  Ska kunna recensera filmer
    - [x]  Se, skapa och ändra i listor med filmer som man vill se (se IMDb:s watchlist)
  - [x]  **En skyddad del**, där endast en administratör kan logga in för att göra följande:
    - [x]  Hantera recensioner och kommentarer (godkänna, ta bort)
    - [x]  CRUD-operationer för filmer
    - [x]  CRUD-operationer för användare

Also look at the accompanying requirements document for more details:
 (https://docs.google.com/document/d/1s32slmmL6FCqguvD06CtB4fWucoPtB8wmaXar3_DvzU/edit#)

From that document I'm missing the following: 

- [x] Sitemap
- [x] The application must be responsive (work well and look good on all screen sizes)

Please see my other issues for smaller bugs that you can also adress, but this prioritized.

**Comment by ghost** [comment]
Yes box

2018-02-28 11:18 GMT+01:00 Axel Olsson <notifications@github.com>:

**Comment by SebastianGerS** [comment]
@axelolsson  @chas-academy/berserkers  
Det mesta av det här är implementerat men har upptäckt vissa buggar när man skapar och lägger till i sina listor så vi får se till att det fungerar, sen är vissa saker lite ointuitiva (för att komma till userpages klickar man tex bara på sitt namn efter att man har loggat in.

Recensera och sätta betyg på filmer kan man bara göra om man är inloggad men vi borde se till att dölja knappar för dessa funktioner för dem som inte är inloggade (vilket inte görs överallt).
För att recensera en film måste man gå in på den filmens specifika sida men för att sätta betyg gör man från catalog viewn.

alla admin cruds är skyddade men vissa vyer som bara borde vara tillgängliga för admin går att komma åt om man är inloggad, det måste vi fixa

Vi har stöd för alla crud operationer på filmer och serier redan. (dock verkar det vara lite problem att tabort serier, får kolla på det)

När det gäller anvädnar cruds för admins så kan man som admins endast avaktivera/aktivera/göra till admin. Tänker att det är dummt att helt ta bort en användare, men man borde också kunna redigera en användares mejl som  mm som admin? 

Det finns stöd i databasen för att kunna ändra status på en recention (godkänna) men det har inte implementerats så det måste fixas, dels genom att skapa en ny flik i admin panelen för detta och dels genom att implementera den logic som krävs för att kunna ändra statusen.

Responsivteten är inte riktigt vad den borde vara, många sidor har store brister när det gäller det så det får vi försöka fixa.

**Comment by axeberg** [comment]
@SebastianGerS Okay, well I'm sure there support for some of the operations I just can't seem to get them working for either of the points above. Hence unchecking these again, I'm testing in the production environment btw.

Here's how I see it, and what I think needs fixing/work for this assignment to be achieve a passable grade:

1. CRUD for movies/tvshows needs work. Instead of adding a submit button for every field wouldn't it be easier with one save button at the end? And then only handling the values that actually have been changed? Some fields seem to throw errors when submitting (tried to input text in the runtime field for Star Wars e.g.).

2. Reviews aren't working at all. What I'm doing wrong?

3. The CRUD for watchlists is also not working at all. What am I doing wrong?

4. CRUD for users is limited to changing their roles and setting them as deleted, which is fine. But I should be able to create new users manually, and update their other fields. Please fix

5. Remove all CSS effects and focus on getting the design for all the views actually implemented or at least usable on a mobile device.

6. Sitemap.

**Comment by SebastianGerS** [comment]
@axelolsson  okej jag förstår ska kolla på dom saker som inte verkar fungera så fort vi hinner.
 
reviews är det inget fel på vad jag kan se, du har skapat en review, dock kan man inte se den pga att den inte var godkänd av admin än (men fixade jag det manuellt i databsen då vi inte har stöd för göra det på annat vis än) samma sak gäller komentarer, så det är inte ett problem med komentarerna i sig utan handlar om att fixa stöd för att admin ska kunna godkänna dem.

watchlisten verkar det ha blivit något fel på, så den får jag undersöka

**Comment by SebastianGerS** [comment]
@axelolsson 

1.  I have improved how titles are updated, thought the way directors/Actors etc are updated is not optimal so meaby I should change it to work in the same way the updating and adding of images for titles now work? Btw the idé with having a update button for each field was that it would allow the admin to quickly updated what ever field he wishes with out having to scroll all the way down to submit his/her update.  It's the same function that handles all of it by checking which keys (name property of the field submitted) that should be updated.

2. Now admins should be able to approve or disprove the reviews (have not added support for deleting reviews at the present moment

3. Watchlists have been fixed,  note however that curently there is only support for items to the watchlist in the userpages

4. admins are now able to update all fields of a user and can also easily create new users

**Comment by axeberg** [comment]
@SebastianGerS 

1. Fair enough.
2. Yup, works fine. Need delete for reviews.
3. ~~Okay, that's fine. I can't seem to reorder them in the list but that's fine - you can remove the ordering of items in the list.~~
4. Yup, works fine!

If you can manage to fix the reviews and the stuff below, I can pass this assignment:

- [x] - Sitemap
- [x] - Some styling fixes (perhaps some of your team members can help out here)?

**Comment by AnnaRoss** [comment]
I will clean up the styling.

@SebastianGerS, we owe you a lot - thank you for being such a trooper and fix everything.

**Comment by ghost** [comment]
you're the man!

Den tor 5 apr. 2018 09:16AnnaRoss <notifications@github.com> skrev:

**Comment by SebastianGerS** [comment]
@AnnaRoss thanks!

@axelolsson ok will add delete for reviews btw what goes wrong when you are trying to reorder the list? (I just tested i again my selfe and it worked fine fore me)

**Comment by axeberg** [comment]
@SebastianGerS Nothing wrong, I just think the UX needs some work.

**Comment by axeberg** [comment]
Alright @chas-academy/berserkers let me know when these issues are deployed to production.

**Comment by axeberg** [comment]
@chas-academy/berserkers anything that I've missed here or is this done?

**Comment by Tokidaze** [comment]
Yes, this is done. You can find the sitemapping in the readme.md
