### ISSUE TITLE
User Personas

### ISSUE THREAD

**Issue by Tokidaze** [chas-academy/berserkers-06-imdb-clone#2]
Personas that may use the website, we need three personas minimum for this project.

**Comment by AnnaRoss** [comment]
@X3n0m0rphose  @Laloo89  @Oleg-Lopes @SebastianGerS 
Status report to fellow team mates: Husse and I have written drafts  to Persona 1 and 2.  Comments of all sorts are highly appreciated (perhaps our Personas consists of 10, 50 or 90% BS - just let us know!).

You find them towards the end of the drive doc  :)

**Comment by ghost** [comment]
Great job, I don't have any thoughts right now but maybe later during the
day :) like the personas -stuff

Den 30 nov. 2017 08:57 skrev "AnnaRoss" <notifications@github.com>:

**Comment by SebastianGerS** [comment]
@axelolsson 

här var väll et mer lämpligt ställe att lägga in detta:
https://docs.google.com/a/chasacademy.se/presentation/d/127hHGr5B8JUE6Tm7uXda1g6kEdsjw5FWkkKnc6vbmHU/edit?usp=sharing

**Comment by axeberg** [comment]
@SebastianGerS fantastic. Thanks for that!
