### ISSUE TITLE
Create User Stories - Website Users

### ISSUE THREAD

**Issue by AnnaRoss** [chas-academy/berserkers-06-imdb-clone#3]
Deconstruct the Epic user story Website Users, provided by the Product Owner Axel Olsson.

**Comment by axeberg** [comment]
Just ping me in any issue with @-sign like on facebook or twitter if you need specific input.

**Comment by SebastianGerS** [comment]
@axelolsson 
https://docs.google.com/a/chasacademy.se/presentation/d/127hHGr5B8JUE6Tm7uXda1g6kEdsjw5FWkkKnc6vbmHU/edit?usp=sharing
