### ISSUE TITLE
Create Prototype | Luser Edition | Desktop

### ISSUE THREAD

**Issue by AnnaRoss** [chas-academy/berserkers-06-imdb-clone#39]

**Comment by SebastianGerS** [comment]
@axelolsson

 https://projects.invisionapp.com/share/N8EWQRNK3#/screens/268772024

skapad av @Tokidaze

**Comment by axeberg** [comment]
@SebastianGerS uhm that one takes me to a mobile layout?

**Comment by SebastianGerS** [comment]
@axelolsson 
https://projects.invisionapp.com/share/N8EWQRNK3#/screens/268760730
https://projects.invisionapp.com/share/N8EWQRNK3#/screens/268760731
https://projects.invisionapp.com/share/N8EWQRNK3#/screens/268760732

sorry I have to change some setting here I think, I'm not getting any notification from here

**Comment by SebastianGerS** [comment]
there's also a button down to the l right with 9 smalsquers that you can push to se all the prototypes at once

**Comment by axeberg** [comment]
@SebastianGerS that's fine, but you haven't really replied to my comments in the prototype.

**Comment by axeberg** [comment]
I don't understand the last link either, is that at another screen-size? Need some context here.

**Comment by SebastianGerS** [comment]
The all three are for the same screensize

The first is the ”home” page
The second is the Movie/tv-show page (togled on movies but looks the sams for series)
The third is  a top-100 list (toggled on movies)

**Comment by axeberg** [comment]
@SebastianGerS okay - but you haven't adressed any of my comments in any of those views. Do I get any say in what the final delivery looks like? :)

**Comment by SebastianGerS** [comment]
Based on your comments @AnnaRoss has been working on a compleatly rewampt design we are hopping to share that design with you today.
