### ISSUE TITLE
Create Wireframe (pen and paper) Luser Edition

### ISSUE THREAD

**Issue by SebastianGerS** [chas-academy/berserkers-06-imdb-clone#4]

**Comment by axeberg** [comment]
Can I see these wireframes please? I'd like to give some feedback.

**Comment by SebastianGerS** [comment]
@axelolsson  lite  hand ritade wireframes följer nedan:

![image uploaded from ios 2](https://user-images.githubusercontent.com/31239260/33836401-9ca4f702-de89-11e7-8a0c-969f707bc935.jpg)

![image uploaded from ios 1](https://user-images.githubusercontent.com/31239260/33836402-9cc11fd6-de89-11e7-9f33-e64f9b5415ee.jpg)

![image uploaded from ios](https://user-images.githubusercontent.com/31239260/33836403-9ce3a45c-de89-11e7-9b88-76a81c6bc782.jpg)

![image uploaded from ios 5](https://user-images.githubusercontent.com/31239260/33836404-9d137290-de89-11e7-9433-789aa3c390ae.jpg)

![image uploaded from ios 4](https://user-images.githubusercontent.com/31239260/33836406-9d328f90-de89-11e7-8430-749df6768655.jpg)

![image uploaded from ios 3](https://user-images.githubusercontent.com/31239260/33836407-9d4de6fa-de89-11e7-9fff-6ae5c9e7424b.jpg)

**Comment by axeberg** [comment]
I can see where this is going but please remember to not put **too much** information about the movie in a list, especially on the mobile layout.
