### ISSUE TITLE
Create Prototype | Power User Edition | Small Screen

### ISSUE THREAD

**Issue by AnnaRoss** [chas-academy/berserkers-06-imdb-clone#40]

**Comment by SebastianGerS** [comment]
@axelolsson 

wirefarme / prototype for conatct-page and user main page
https://www.figma.com/file/BXVaTn2J78I13eH3awna0qim/Untitled

**Comment by axeberg** [comment]
@SebastianGerS this looks totally different from the other design and uses a different tool...
