### ISSUE TITLE
Movies Controller

### ISSUE THREAD

**Issue by Oleg-Lopes** [chas-academy/berserkers-06-imdb-clone#60]

**Comment by axeberg** [comment]
@Oleg-Lopes Size?

**Comment by AnnaRoss** [comment]
Hi, @Oleg-Lopes :smiley:  is there something I or someone else in the team could do  to help concerning controllers?

**Comment by SebastianGerS** [comment]
index,show,edit,update and destory functions are done

still need to add create and store functionality (we can reeus some things from the seeders)
