### ISSUE TITLE
Create Prototype | Luser Edition | Small Screen

### ISSUE THREAD

**Issue by SebastianGerS** [chas-academy/berserkers-06-imdb-clone#7]

**Comment by axeberg** [comment]
Any progress on these?

**Comment by SebastianGerS** [comment]
@axelolsson 

wireframe for start page 
![mobilostart](https://user-images.githubusercontent.com/31239260/33837306-378a337a-de8c-11e7-95d9-eb5769966e83.png)

made by @X3n0m0rphose

**Comment by SebastianGerS** [comment]
@axelolsson 

https://projects.invisionapp.com/share/N8EWQRNK3#/screens/268772024

skapad av @Tokidaze

**Comment by axeberg** [comment]
@SebastianGerS added comments
