### ISSUE TITLE
Update README to contain proper installation instructions

### ISSUE THREAD

**Issue by ghost** [chas-academy/berserkers-06-imdb-clone#95]
closes #13
At the moment we are adding the .env-file to the .gitignore (which is correct) but we could provide a .env.example file that the developer can use as a baseline for getting the project up and running.

The we should also add installation instructions for getting the project started. For example:

1. Clone the repository to your local machine.
2. Setup SSH-keys and the Homestead VM if you haven't already.
3. Start the VM.
4. Inside the project root run `composer install`
5. Inside the project root rename the `.env.example` file to `.env`, make sure you have the correct app-key set (i.e. `php artisan key:generate`) any other default configuration should work.
6. Add berserkers.test to both the Homestead.yaml config and your `/etc/hosts/` or Windows hosts file.
7. `vagrant reload --provision`
8. Browse to http://berserkers.test
9. Develop like the wind!

**Comment by axeberg** [comment]
@chas-academy/berserkers 

Sersiously. Do this now.

**Comment by SebastianGerS** [comment]
Ok... will try to find the time

**Comment by SebastianGerS** [comment]
@chas-academy/berserkers 
@axelolsson 

I have added the .env.example file to the dev branch the rebased  Components (git rebase dev  (in the Components branch). So now the .env.example file can be found in thoes branches. so rebase or merge it in to your branchen if you need it.

Will look att updating the readme file leater tonight

**Comment by SebastianGerS** [comment]
But just realised that I shouled hav done it the other way around should had crated the file in components and after rebase merged it into dev o well

**Comment by axeberg** [comment]
@SebastianGerS thanks for the quick response, I think you managed to re-open this with the second mention of the issue though :).

Closing this. Good job 👍
